name: Bulk TikTok Download with Psiphon VPN and Proxy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tiktok-bulk-download:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download Psiphon
      - name: Download Psiphon
        run: |
          wget https://psiphon.ca/psiphon-tunnel-core-latest-linux -O psiphon
          chmod +x psiphon

      # Step 3: Start Psiphon VPN and Save Logs
      - name: Start Psiphon VPN
        run: |
          mkdir -p logs
          ./psiphon -country SG > logs/psiphon.log 2>&1 &
          sleep 15 # Wait for Psiphon to establish a connection

      # Step 4: Configure Proxy Environment Variables
      - name: Configure Proxy
        run: |
          export HTTP_PROXY="http://127.0.0.1:8080"
          export HTTPS_PROXY="http://127.0.0.1:8080"
          export ALL_PROXY="socks5://127.0.0.1:1080"
        shell: bash

      # Step 5: Verify VPN Connection (Check IP Address)
      - name: Verify VPN Connection
        run: |
          curl -I https://ipinfo.io
        shell: bash

      # Step 6: Install 7zip
      - name: Install 7zip
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full

      # Step 7: Download and Unzip FFMPEG
      - name: Setup FFMPEG
        run: |
          wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z
          7z x ffmpeg-release-essentials.7z -o"ffmpeg"
          mv ffmpeg/* .

      # Step 8: Update yt-dlp
      - name: Update yt-dlp
        run: |
          if [ -f "yt-dlp" ]; then
              ./yt-dlp -U
          else
              echo "yt-dlp not found! Ensure it's included in the repo."
          fi

      # Step 9: Run Batch Script
      - name: Run TikTok Download Script
        run: |
          chmod +x tiktok.bat
          ./tiktok.bat
        shell: bash

      # Step 10: Upload Logs and Download Folder as Artifacts
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: psiphon-logs
          path: logs/

      - name: Upload Download Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tiktok
          path: tiktok/
