name: TikTok API Runner

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
jobs:
  run-tiktok-api:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository (your own repository)
      - name: Checkout your repository
        uses: actions/checkout@v3

      # Step 2: Clone the TikTok-Api repository
      - name: Clone TikTok-Api repository
        run: git clone https://github.com/Daan-Grashoff/TikTok-Api.git

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 4: Install dependencies for TikTok-Api
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install
          pip install -r TikTok-Api/requirements.txt
      
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libvpx9 libevent-2.1-7t64 libopus0 libgstreamer-plugins-base1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libflite1 libavif16 libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 libgles2 gstreamer1.0-libav
      
      
      # Step 5: List All Files and Folders (Using bash)
      - name: List All Files and Folders
        run: |
          find . -type f

      # Step 6: Run the TikTok API script
      - name: Run TikTok API
        working-directory: TikTok-Api
        env:
          CUSTOM_VERIFY_FP: ${{ secrets.CUSTOM_VERIFY_FP }}
        run: |
          python -m examples.get_trending
          python -m examples.download_tiktok
          python -m examples.get_a_users_videos
          python -m examples.get_tiktoks_by_hashtag
          python -m examples.get_tiktoks_by_sound
          python -m examples.get_tiktoks_by_username

      # Step 6: Run the TikTok API script
      - name: Run my code
        env:
          CUSTOM_VERIFY_FP: ${{ secrets.CUSTOM_VERIFY_FP }}
        run: |
          python -m examples.get_trending

      # Step 7: Save the output as an artifact
      - name: Upload output
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: tiktok-output
          path: TikTok-Api/output/
