name: TikTok API Runner

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  run-tiktok-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install TikTokApi playwright
          python -m playwright install

      # Run the TikTok API script
      - name: Run TikTok API
        env:
          CUSTOM_VERIFY_FP: ${{ secrets.CUSTOM_VERIFY_FP }}
        run: |
          python -m examples.get_trending

      # Save the output as an artifact
      - name: Upload output
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: tiktok-output
          path: output/
