name: Scrape TikTok Hashtag

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install Node.js 18.x and npm
      run: |
        # Install Node.js 18.x and npm
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install dependencies
      run: |
        # Install system dependencies required by TikTok scraper
        sudo apt-get update
        sudo apt-get install -y libpixman-1-dev libjpeg-dev libgif-dev

    - name: Install tiktok-scraper globally using npm
      run: |
        # Install tiktok-scraper globally with npm
        npm install -g tiktok-scraper

    - name: Scrape TikTok posts for the hashtag "comdy"
      id: scrape
      run: |
        # Run the scraper to collect TikTok posts
        mkdir output
        npx tiktok-scraper hashtag comdy -n 100 -d -f all --zip --filepath ./output/comdy

    - name: Convert JSON to Excel
      run: |
        # Convert the JSON data to Excel format
        mkdir ./output/xlsx
        cd ./output
        node -e "
          const fs = require('fs');
          const xlsx = require('xlsx');
          const jsonData = require('./comdy.json');
          const ws = xlsx.utils.json_to_sheet(jsonData.collector);
          const wb = xlsx.utils.book_new();
          xlsx.utils.book_append_sheet(wb, ws, 'TikTok Posts');
          xlsx.writeFile(wb, './xlsx/comdy.xlsx');
        "

    - name: Upload JSON, CSV, Excel, and ZIP artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tiktok-hashtag-scrape-results
        path: |
          ./output/comdy.json
          ./output/comdy.csv
          ./output/xlsx/comdy.xlsx
          ./output/comdy.zip
